name: Unit Tests

on: push

jobs:
  build_job:
    name: Unit Tests Check
    runs-on: ubuntu-latest
    steps:
      # Checkout the latest commit
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Java JDK
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Run Unit Test
      - name: Run Unit Test
        run: ./gradlew testDebugUnitTest